export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_ORDERED_PRODUCTS = 'SET_ORDERED_PRODUCTS';
export const SET_LOADING_PRODUCTS = 'SET_LOADING_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const SUBSTRACT_FROM_CART = 'SUBSTRACT_FROM_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
